### ISSUE TITLE
Name clash with other D bindings

### ISSUE THREAD

**Issue by bohlender** [theoldmoon0602/d-capstone#1]
Hey @theoldmoon0602 ,

looks like we had the same idea with making D bindings for Capstone. Unfortunately, you've gone for the same name as I did (https://github.com/bohlender/capstone-d), as I found out just yesterday. The main difference between the packages seems that you're providing a C-like API, while I provide idiomatic D bindings - both have its use of course.

To avoid confusion, and considering that it is a very fresh package, would you consider using a different name? Besides, if you're interested in using Capstone from D, you are of course invited to team up with me in finishing the idiomatic D bindings.

**Comment by theoremoon** [comment]
Hi @bolhlender

Thanks for your message. I will change the repository name into another one.

> if you're interested in using Capstone from D, you are of course invited to team up with me in finishing the idiomatic D bindings.

That's very tempting but I think I'll pass. Actually I'm just making a small wrapper for my project. I hope your project will make it big.

Thank you :)

**Comment by bohlender** [comment]
Thanks for your fast reply!

> I will change the repository name into another one.

It's great to hear that it is not an issue for you, however the repository name is not that much of a problem - it's the naming in the D package management (DUB). Are you planning to update that name too?

> That's very tempting but I think I'll pass. Actually I'm just making a small wrapper for my project.

That's fine. You're still welcome in case you change your mind in the future. Good luck with your project :)

**Comment by theoremoon** [comment]
hi @bohlender .

 I have just removed dub package capstone-d temporarily (recreate as d-capstone later), so now you can use "capstone-d" as your package name.

**Comment by bohlender** [comment]
Thanks! :+1:
